# Generated by Django 5.2.4 on 2025-08-03 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_galleryitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_gallery/%Y/%m/')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate Event'), ('social', 'Social Gathering'), ('birthday', 'Birthday Party'), ('conference', 'Conference'), ('exhibition', 'Exhibition')], default='wedding', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Gallery Image',
                'verbose_name_plural': 'Event Gallery Images',
                'ordering': ['-event_date', '-upload_date'],
                'permissions': [('can_manage_event_gallery', 'Can manage event gallery images')],
            },
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.AddIndex(
            model_name='eventgalleryimage',
            index=models.Index(fields=['event_type', 'is_active'], name='event_event_event_t_b392d0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventgalleryimage',
            index=models.Index(fields=['is_featured'], name='event_event_is_feat_341ec8_idx'),
        ),
        migrations.AddIndex(
            model_name='eventgalleryimage',
            index=models.Index(fields=['event_date'], name='event_event_event_d_21dd15_idx'),
        ),
    ]
