# Generated by Django 5.2.4 on 2025-08-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventgalleryimage_delete_galleryitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GallaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='user_portfolio/')),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.portfoliocategory')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.DeleteModel(
            name='EventGalleryImage',
        ),
    ]
