# Generated by Django 5.2.4 on 2025-08-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_gallaryitem_delete_eventgalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="Name of the icon from your icon library (e.g., 'fa-calendar')", max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_type', models.CharField(choices=[('FIXED', 'Fixed Price'), ('HOURLY', 'Hourly Rate'), ('CUSTOM', 'Custom Quote')], default='FIXED', help_text='How the price is calculated', max_length=10)),
                ('show_button', models.BooleanField(default=True, help_text='Whether to display the action button for this service')),
                ('button_text', models.CharField(default='Get Started', help_text='Text to display on the button', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
    ]
